### ISSUE TITLE
Rename this repo/driver?

### ISSUE THREAD

**Issue by LindsayHill** [napalm-automation-community/napalm-brocade-slxos#5]
Brocade IP products have different operating systems:

- NetIron - used on the MLXe product line. Older OS, with limited Netconf support. Only practical way of automating this is via CLI/screen-scraping.
- NOS - used on the VDX product line (e.g. VDX 6740, 6940). More modern OS, includes REST & Netconf interfaces.
- SLX-OS - used on the new SLX 9850, 9540, 9140, 9240 switches/routers. This is based upon NOS, with similar APIs, but more operational state info available via API. 

It's not a perfect comparison, but roughly, NetIron is equivalent to legacy IOS from an automation point of view, whereas NOS/SLX-OS are more like IOS-XR. SLX-OS is the 'future' OS, but NetIron is going to be around for a few years yet.

PR #1 here is designed to work with SLX-OS & NOS, leveraging the pyswitchlib library that works with both operating systems. But it is not going to work for NetIron systems.

There is interest in developing a NetIron driver for MLXe systems. This would probably start as a fork of the IOS driver. 

Should we rename this driver to something like napalm-nos or napalm-slxos, and then create a new driver napalm-netiron, for MLXe devices? 

Probably good to figure it out now, before code gets merged and people start using it :)

Thoughts?

**Comment by ktbyers** [comment]
I think we should do something like napalm-brocade-nos or napalm-brocade-slos.

Personally, I think `napalm-platform` is going to get too confusing as the number of drivers increases (i.e. I will see `napalm-nos` and not know what it is refers to). 

I like to have the driver name be pretty self-explanatory.

**Comment by LindsayHill** [comment]
Yeah, I also like the idea of `napalm-<vendor>-<platform>`, similar to what you're doing with netmiko.

**Comment by mirceaulinic** [comment]
Hi @LindsayHill - thanks for clarifying this. I was really wondering what platforms is this driver going to support. At some point I just assumed that all of them would be covered. Certainly, I was wrong.
Yes, `napalm-<vendor>-<platform>` makes sense to me too. Let's see if @dbarrosop agrees and then I think we can rename.

Cheers,
Mircea

**Comment by dbarrosop** [comment]
No problem, we can rename to `napalm-brocade-nos` or `napalm-brocade-slxos`. @LindsayHill feel free to pick one and I will rename the repo.

**Comment by LindsayHill** [comment]
Hmmm, now I guess I better decide which one makes most sense. NOS is much more widely deployed today, but SLX-OS is the 'new' OS and should see more deployment from now on. Will doublecheck with someone else internally to see if they'll be using the "SLX-OS" or "NOS" name more.

**Comment by LindsayHill** [comment]
OK, I think we should go with `napalm-brocade-slxos`. This will also work for NOS-based platforms (VDX). In future we can have `napalm-brocade-netiron` if/when we develop a driver for MLXe devices (these run NetIron).

**Comment by jedelman8** [comment]
Not sure thoughts on this but adding "-<api-type>" could be helpful too. Often have to explain that one only used an API and not SSH.

**Comment by jedelman8** [comment]
To clarify, knowing eos uses eapi is helpful like eos-eapi, or cisco-nxos-nxapi, or cisco-ios-ssh , etc.

**Comment by mirceaulinic** [comment]
So the name for this one would be `napalm-brocade-slxos-api`? :)

**Comment by LindsayHill** [comment]
In this case I'm not in favor of adding `-<api>`, if only because the driver should retain some flexibility to implement things as needed - e.g. maybe it mainly uses the API, but needs to use SSH for one specific thing.

FWIW, SLXOS will be almost all API, while NetIron will be SSH-based.

**Comment by dbarrosop** [comment]
I don't think the name should encode too much information TBH, that's what the documentation is for. I will go with `napalm-brocade-slxos`.

**Comment by dbarrosop** [comment]
This is done, feel free to reopen or comment if there is still some debate around the name :)

**Comment by ktbyers** [comment]
I agree that we shouldn't encode the transport (api versus ssh) into the Package name.
