### ISSUE TITLE
ownsership for brocade-slxos driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation-community/napalm-brocade-slxos#8]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @shivharis @LindsayHill

If you have questions/comments let me know.

Regards

**Comment by LindsayHill** [comment]
Happy to become maintainer for this repo...and to hopefully actually get useful stuff merged. It looks like I will have some involvement in this space as we enter our brave new world at Extreme.

**Comment by dbarrosop** [comment]
Awesome! I think you should be able to rename the repo yourself if you have to but otherwise, let me know and I will gladly do it :)
